default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  username: postgres
  database: rootlydemobot
  password: Test1234


test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  username: postgres
  database: rootlydemobot
  password: Test1234

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  username: postgres
  database: rootlydemobot
  password: Test1234

# production:
#   url: postgres://admin:pE3TH5XvijZ1gTfFBc3pd6IMHEnC8MBI@dpg-cgntdv8rddl9mmo4b0b0-a/rootlydemobot
#   # url: postgres://admin:pE3TH5XvijZ1gTfFBc3pd6IMHEnC8MBI@dpg-cgntdv8rddl9mmo4b0b0-a.oregon-postgres.render.com/rootlydemobot
#   username: admin
#   database: rootlydemobot
#   password: pE3TH5XvijZ1gTfFBc3pd6IMHEnC8MBI